var cards = [
  [1,"Alligator's Sword","Beast",0,"","Earth","4","1500","1200","ey, dis mighty lissard man can swing his sword so fast, dat it's more dan da speed a sound!"],
  [2,"Alligator's Sword Dragon","Dragon","Fusion","Effect","Wind","5","1700","1500","\"Baby Dragon\" + \"Alligator's Sword\". This card can attack your opponent directly if the only face-up monsters they control are EARTH, WATER OR FIRE."],
  [3,"Axe Raider","Warrior",0,"","Earth","4","1700","1150","An axe-wielding monster of tremendous strength and agility."],
  [4,"Baby Dragon","Dragon",0,"","Wind","3","1200","700","Much more than just a child, this dragon is gifted with untapped power."],
  [5,"Backup Soldier","Trap",0,"","-","-","-","-","While there are 5 or more monsters in your Graveyard: Target up to 3 non-Effect Monsters with 1500 or less ATK in your Graveyard; add them to your hand."],
  [6,"Buster Blader","Warrior",0,"Effect","Earth","7","2600","2300","Gains 500 ATK for each Dragon monster your opponent controls or is in their GY."],
  [7,"Call of the Haunted","Trap",0,"","-","-","-","-","Activate this card by targeting 1 monster in your GY; Special Summon that target in Attack Position. When this card leaves the field, destroy that monster. When that monster is destroyed, destroy this card."],
  [8,"Card of Safe Return","Spell",0,"","-","-","-","-","When a monster is Special Summoned from your Graveyard, you can draw 1 card."],
  [9,"Chain Destruction","Trap",0,"","-","-","-","-","When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller's hand and Main Deck."],
  [10,"Change of Heart","Spell",0,"","-","-","-","-","Target 1 monster your opponent controls; take control of it until the End Phase."],
  [11,"Flame Cerebrus","Pyro",0,"","Fire","6","2100","1800","Known to many as the \"Burning Executioner\", this monster is capable of burning enemies to cinders."],
  [12,"Gadget Soldier","Machine",0,"","Fire","5","1800","2000","A rust-free machine warrior born to battle."],
  [13,"Gamma the Magnet Warrior","Rock",0,"","Earth","4","1500","1800","Alpha, Beta, and Gamma meld as one to form a powerful monster."],
  [14,"Gemini Elf","Spellcaster",0,"","Earth","4","1900","900","Elf twins that alternate their attacks."],
  [15,"Giant Trunade","Spell",0,"","-","-","-","-","Return all Spell and Trap Cards on the field to the hand."],
  [16,"Goblin Attack Force","Warrior",0,"Effect","Earth","4","2300","0","If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn."],
  [17,"Graceful Dice","Spell",0,"","-","-","-","-","Roll a six-sided die. All monsters you currently control gain ATK/DEF equal to the result x 100, until the end of this turn."],
  [18,"Gradius","Machine",0,"","Light","4","1200","800","A high-performance jet fighter with power capsules for variable attack capabilities."],
  [19,"Harpie's Feather Duster","Spell",0,"","-","-","-","-","Destroy all Spell and Trap Cards your opponent controls."],
  [20,"Headless Knight","Fiend",0,"","Earth","4","1450","1700","A haunted spirit of a falsely accused knight who wanders in search of truth and justice."],
  [21,"Island Turtle","Aqua",0,"","Water","4","1100","2000","A huge turtle that is often mistaken for an island."],
  [22,"Magic Cylinder","Trap",0,"","-","-","-","-","When an opponent's monster declares an attack: Target the attacking monster; negate the attack, and if you do, inflict damage to your opponent equal to its ATK."],
  [23,"Magic Jammer","Trap",0,"","-","-","-","-","When a Spell Card is activated: Discard 1 card; negate the activation, and if you do, destroy it."],
  [24,"Monster Reborn","Spell",0,"","-","-","-","-","Target 1 monster in either GY; Special Summon it."],
  [25,"Morphing Jar #2","Rock",0,"Effect","Earth","3","800","700","FLIP: Shuffle all monsters on the field into the Deck. Then, each player excavates cards from the top of their Deck, until they excavate the same number of monsters they shuffled into their Main Deck. Special Summon all excavated Level 4 or lower monsters in face-down Defense Position, also send the remaining cards to the Graveyard."],
  [26,"Mystical Space Typhoon","Spell",0,"","-","-","-","-","Target 1 Spell/Trap on the field; destroy that target."],
  [27,"Nimble Momonga","Beast",0,"Effect","Earth","2","1000","100","When this card is destroyed by battle and sent to the Graveyard: Gain 1000 Life Points, then you can Special Summon any number of \"Nimble Momongas\" from your Deck in face-down Defense Position."],
  [28,"Penguin Soldier","Aqua",0,"Effect","Water","2","750","500","FLIP: You can target up to 2 monsters on the field; return those targets to the hand."],
  [29,"Polymerization","Spell",0,"","-","-","-","-","Fusion Summon 1 Fusion Monster from your Extra Deck, using monsters from your hand or field as Fusion Material."],
  [30,"Sangan","Fiend",0,"Effect","Dark","3","1000","600","If this card is sent from the field to the GY: Add 1 monster with 1500 or less ATK from your Deck to your hand, but you cannot activate cards, or the effects of cards, with that name for the rest of this turn. You can only use this effect of \"Sangan\" once per turn."],
  [31,"Slot Machine","Machine",0,"","Dark","7","2000","2300","The machine's ability is said to vary according to its slot results."],
  [32,"The Gross Ghost of Fled Dreams","Fiend",0,"","Dark","4","1300","1800","This monster feeds on the dreams of an unwary sleeper, dragging the victim into eternal slumber."],
  [33,"Tiger Axe","Beast-Warrior",0,"","Earth","4","1300","1100","A fast and powerful axe-wielding beast-warrior."],
  [34,"Torrential Tribute","Trap",0,"","-","-","-","-","When a monster(s) is Summoned: Destroy all monsters on the field."],
  [35,"Tribute to the Doomed","Spell",0,"","-","-","-","-","Discard 1 card, then target 1 monster on the field; destroy it."],
  [36,"Witch of the Black Forest","Spellcaster",0,"Effect","Dark","4","1100","1200","If this card is sent from the field to the GY: Add 1 monster with 1500 or less DEF from your Deck to your hand, but you cannot activate cards, or the effects of cards, with that name for the rest of this turn. You can only use this effect of \"Witch of the Black Forest\" once per turn."],
  [37,"Zombyra the Dark","Warrior",0,"Effect","Dark","4","2100","500","This card cannot attack your opponent directly. If this card destroys a monster by battle: This card loses 200 ATK."]
]